version: "3.7"

services:

  wordpress:
    hostname: ${HOSTNAME}
    container_name: wordpress
    image: wordpress:5.3.2
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.wordpress.entrypoints=websecure
      - traefik.http.routers.wordpress.tls.certresolver=le
      - traefik.http.services.wordpress.loadbalancer.server.port=80
      - traefik.docker.network=traefik-proxy
    networks:
      traefik-proxy:
      default:

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      default:
    volumes:
      - ./db:/var/lib/mysql      

networks:
  traefik-proxy:
    name: traefik-proxy
    external: false
